name: Build and Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:
     
permissions:
  contents: write
  
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build
          

      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
